server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: petition
    password: petition
    dirver-class-name: oracle.jdbc.driver.OracleDriver
    #HikariCP配置
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

pebble:
  suffix:
  cache: false